### ISSUE TITLE
How to tune tusimple_lanenet.yaml for better accuracy?

### ISSUE THREAD

**Issue by zoombinis** [MaybeShewill-CV/lanenet-lane-detection#485]
Hi, how can we learn more about what the config parameters are doing in?: config/tusimple_lanenet.yaml

Some are intuitive, but others I'm not sure what they might do. I'm experiencing accuracy issues where lanes are not always detected that I'd like to hopefully solve by tuning the sensitivity but I'm not sure which parameters to consider.

I am especially curious about these sections (I see some comments, but still not sure what impact on performance/accuracy some of these may have):

```yaml
AUG:
    RESIZE_METHOD: 'stepscaling' # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: [720, 720] # (width, height), for unpadding
    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling
    MAX_SCALE_FACTOR: 2.0  # for stepscaling
    MIN_SCALE_FACTOR: 0.75  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
    TRAIN_CROP_SIZE: [512, 256]  # crop size for training
    EVAL_CROP_SIZE: [512, 256]  # crop size for evaluating
    CROP_PAD_SIZE: 32
    MIRROR: True
    FLIP: False
    FLIP_RATIO: 0.5
    RICH_CROP:
        ENABLE: False
        BLUR: True
        BLUR_RATIO: 0.2
        MAX_ROTATION: 15
        MIN_AREA_RATIO: 0.5
        ASPECT_RATIO: 0.5
        BRIGHTNESS_JITTER_RATIO: 0.5
        CONTRAST_JITTER_RATIO: 0.5
        SATURATION_JITTER_RATIO: 0.5
DATASET:
    NUM_CLASSES: 2
    PADDING_VALUE: [127.5, 127.5, 127.5]
    MEAN_VALUE: [0.5, 0.5, 0.5]
    STD_VALUE: [0.5, 0.5, 0.5]
    CPU_MULTI_PROCESS_NUMS: 8
```
